require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'Test' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'jesster2k10-react-native-range-slider', :path => '../node_modules/@jesster2k10/react-native-range-slider'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'react-native-fast-video', :path => '../node_modules/react-native-fast-video'

  pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

  pod 'react-native-video-cache', :path => '../node_modules/react-native-video-cache'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  target 'TestTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
